# DATA_PATH = '<path for your resume/job description file>'
DATA_PATH = '/Users/takshgirdhar/Desktop/COSC421_Project/Data/raw_data.csv'
# DATA_PATH = '/Users/kusshsatija/Desktop/COSC421/COSC421Project/Data/raw_data.csv'
# SKILL_FILE_PATH = '<path for the skill-set file>'
SKILL_FILE_PATH = '/Users/takshgirdhar/Desktop/COSC421_Project/Data/Skillset.xlsx'
# SKILL_FILE_PATH = '/Users/kusshsatija/Desktop/COSC421/COSC421Project/Data/input/Skillset.xlsx'
