# DATA_PATH = '<path for your resume/job description file>'
DATA_PATH = '/Users/takshgirdhar/Desktop/COSC421_Project/Job-Description-Parser-master/Resume_JD_parser/input/raw_data.csv'
# DATA_PATH = '/Users/kusshsatija/Desktop/COSC421/COSC421Project/Job-Description-Parser-master/Resume_JD_parser/input/raw_data.csv'
# SKILL_FILE_PATH = '<path for the skill-set file>'
SKILL_FILE_PATH = '/Users/takshgirdhar/Desktop/COSC421_Project/Job-Description-Parser-master/Resume_JD_parser/input/Skillset.xlsx'
# SKILL_FILE_PATH = '/Users/kusshsatija/Desktop/COSC421/COSC421Project/Job-Description-Parser-master/Resume_JD_parser/input/Skillset.xlsx'